// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/huypq02/secure-file-vault/internal/config"
	"github.com/huypq02/secure-file-vault/internal/domain"
	"github.com/huypq02/secure-file-vault/internal/infrastructure/db"
	"github.com/huypq02/secure-file-vault/internal/infrastructure/external"
	"github.com/huypq02/secure-file-vault/internal/infrastructure/scheduler"
	"github.com/huypq02/secure-file-vault/internal/infrastructure/storage"
	"github.com/huypq02/secure-file-vault/internal/interface/handler"
	"github.com/huypq02/secure-file-vault/internal/interface/router"
	"github.com/huypq02/secure-file-vault/internal/usecase/file"
)

// Injectors from wire.go:

func InitializeApp() (domain.Application, error) {
	configProvider := config.NewConfig()
	databaseConfig := config.ProvideDatabaseConfig(configProvider)
	connection, err := db.NewConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	fileRepository := db.NewFileRepository(connection)
	storageConfig := config.ProvideStorageConfig(configProvider)
	s3API, err := storage.NewS3Client(storageConfig)
	if err != nil {
		return nil, err
	}
	storageService := storage.NewS3StorageService(s3API, storageConfig)
	downloadFileUsecase := file.NewDownloadFileUsecase(fileRepository, storageService)
	idService := external.NewIDService()
	uploadFileUsecase := file.NewUploadFileUsecase(fileRepository, storageService, idService)
	fileHandler := handler.NewFileHandler(downloadFileUsecase, uploadFileUsecase)
	domainRouter := router.NewRouter(fileHandler)
	domainScheduler := scheduler.NewScheduler(fileRepository, storageService)
	application := NewApp(domainRouter, domainScheduler)
	return application, nil
}
